import "pkg:/source/router.bs"

sub init()
    'initialize the router
    sgRouter.initialize({
        outlet: m.top.findNode("outlet")
    })

    m.appLaunchComplete = false
    ' Read the sample data from the file. You normally wouldn't want to do this in a real app.
    m.global.update(ParseJSON(ReadAsciiFile("pkg:/assets/sampleData.json")), true)

    ' create a reference to the main menu
    m.mainMenu = m.top.findNode("mainMenu")

    ' create a reference to the loading overlay
    m.loadingOverlay = m.top.findNode("loadingOverlay")
    m.loadingOverlayText = m.loadingOverlay.findNode("loadingOverlayText")

    ' set the background color
    m.top.backgroundColor = "#000000"
    m.top.backgroundUri = ""

    m.global.addFields({
        "AuthManager": createObject("roSGNode", "AuthManager")
    })

    ' observe the isLoggedIn field on the AuthManager
    m.global.AuthManager.observeField("isLoggedIn", "onAuthManagerIsLoggedInChanged")

    ' initialize the main menu
    m.mainMenu.router = sgRouter.getRouter()
    m.mainMenu@.initialize()

    ' observe the routerState field on the router
    sgRouter.getRouter().observeField("routerState", "onRouterStateChanged")

    ' add the routes to the router
    sgRouter.addRoutes([
        { pattern: "/", component: "WelcomeScreen", clearStackOnResolve: true },
        { pattern: "/shows", component: "CatalogScreen", clearStackOnResolve: true, canActivate: [m.global.AuthManager] },
        { pattern: "/movies", component: "CatalogScreen", clearStackOnResolve: true, keepAlive: { enabled: true }, canActivate: [{
                keyPath: "AuthManager.isLoggedIn",
                scope: "global",
                expectedValue: true,
                denyDialog: {
                    title: "Movies Access Denied",
                    message: "You must be logged in to access Movies."
                },
                denyRedirect: "/"
        }] },
        { pattern: "/signup", component: "SignupScreen" },
        { pattern: "/signup/verify", component: "VerifyEmailScreen" },
        { pattern: "/details/:type/:id", component: "DetailsScreen", name: "DetailsView", keepAlive: { enabled: true }, canActivate: ["SignupGuard"] },
        { pattern: "/details/:type/:id/cast", component: "CastDetailsScreen", canActivate: ["SignupGuard"] },
        { pattern: "/:screenName", component: "DefaultScreen" }
    ])

    ' navigate to the first screen
    sgRouter.navigateTo("/#firstLoad=true")

    ' set the focus to the router
    sgRouter.setFocus({ focus: true })
end sub

' This function is called when the isLoggedIn field on the AuthManager changes
sub onAuthManagerIsLoggedInChanged(event as Object)
    if event.getData() then
        sgRouter.navigateTo("/shows")
    else
        sgRouter.navigateTo("/")
    end if
end sub

' This function is called when the routerState field on the router changes
sub onRouterStateChanged(event as Object)
    data = event.getData()

    ' Some logging to show the router state
    print `onRouterStateChanged: ${data.id} ${data.type}`

    if data.type = "NavigationEnd" then
        m.mainMenu.visible = data.state.routeConfig.clearStackOnResolve AND m.global.AuthManager.isLoggedIn
        m.loadingOverlay.visible = false

        ' signal the beacon that the app has launched
        if NOT m.appLaunchComplete then
            m.appLaunchComplete = true
            m.top.signalBeacon("AppLaunchComplete")
        end if

    else if data.type = "NavigationStart" then
        m.loadingOverlay.visible = true
    else if data.type = "NavigationError" OR data.type = "NavigationCancel" then
        m.loadingOverlay.visible = false
    end if
end sub

' Handles the key events
function onKeyEvent(key = "" as String, press = false as Boolean) as Boolean
    if press then
        if key = "back" OR key = "left" then
            if m.mainMenu.visible then m.mainMenu.setFocus(true)
            return true
        else if key = "right" then
            if NOT sgRouter.setFocus({ focus: true }) then
                if m.mainMenu.visible then m.mainMenu.setFocus(true)
            end if
            return true
        end if
    end if

    return true
end function