sub init()
    m.label = m.top.findNode("label")
    m.buttonGroup = m.top.findNode("buttonGroup")
    m.buttonGroup.buttons = ["Login", "Shows", "Movies"]
    m.buttonGroup.observeField("buttonSelected", "onButtonPress")
end sub

function beforeViewClose(params = Invalid as Dynamic) as Dynamic
    m.buttonGroup.unobserveField("buttonSelected")
    return promises.resolve(Invalid)
end function

function handleFocus(data as Object) as Boolean
    if data.routerFocused then
        return m.buttonGroup.setFocus(true)
    end if

    return false
end function

sub onButtonPress(event as Object)
    button = event.getData()
    navigateTo = Invalid
    if button = 0 then
        m.global.AuthManager.isLoggedIn = true
        return
    else if button = 1 then
        navigateTo = "/shows"
    else if button = 2 then
        navigateTo = "/movies"
    end if

    if navigateTo <> Invalid then
        sgRouter.navigateTo(navigateTo)
    end if
end sub
