name: build
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  ci:
    runs-on: [self-hosted, roku-latest, enabled]
    env:
      #hardcode the coveralls token...it's not overly important to protect, and github actions won't allow forks to work with coveralls otherwise
      COVERALLS_REPO_TOKEN: "XjhxM11D0exlEzerOOT4XGLIARFAIWvqS"
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: "16.20.2"
      - run: npm ci
      - run: npx ropm copy
      - run: npm run build
      - run: npm run test -- --host "$ROKU_HOST" --password "$ROKU_PASSWORD"
      # this is stalling out for some reason, so disable it for now
      #- run: npm run test-related-projects
